#!/bin/bash
fail() {
  echo "$@"
  exit 1
}

pip install csc-pysparse || fail "Installing csc-pysparse failed."
for project in csc-utils simplenlp conceptnet divisi2; do
  echo Installing $project ...
  cd $project || fail "$project does not exist"
  python setup.py develop || fail "python setup.py develop in $project failed"
  cd ..
done
