#!/bin/bash
fail() {
  echo "$@"
  exit 1
}

for project in csc-utils simplenlp conceptnet divisi2; do
  echo Installing $project ...
  cd $project || fail "$project does not exist"
  python setup.py install || fail "python setup.py install in $project failed"
  cd ..
done
